version: '3'

services:
  nginx:
    container_name: Nginx

    build:
      context: .
      dockerfile: nginx.dockerfile

    ports:
      - 4000:80

    volumes:
      - ./src:/var/www/html

    restart: always

    depends_on:
      - mysql
  
  mysql: 
    container_name: MariaDB

    image: mariadb:10.5

    ports:
      - 3307:3306

    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

    volumes:
      - ./mysql:/var/lib/mysql

    restart: always
  
  php:
    container_name: PHP
    
    build:
      context: .
      dockerfile: php.dockerfile
    
    volumes:
      - ./src:/var/www/html

    restart: always