version: '3'

services:
  nginx:
    container_name: webapp

    build:
      context: .
      dockerfile: nginx.dockerfile

    ports:
      - 4000:80

    volumes:
      - ./src:/var/www/html

    restart: always

    environment:
      - NGINXUSER=laravel
      - NGINXGROUP=laravel

  mysql: 
    container_name: database

    image: mysql:latest

    ports:
      - 3307:3306

    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

    # volumes:
    #   - ./mysql:/var/lib/mysql

    restart: always

  phpmyadmin:
    container_name: phpmyadmin

    image: phpmyadmin
    
    restart: always
    
    ports:
      - 8081:80

    environment:
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

    depends_on:
      - mysql