version: '3'

services:
  nginx:
    container_name: Nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 4000:80
    volumes:
      - ./src:/var/www/html

    depends_on:
      - php

  php:
    container_name: PHP
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html